name: 'Build Extension'
on: push
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 1.8'
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: 'Build Extension'
        run: ant extensions
      - name: 'Upload to Artifacts'
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MIT AI2 Companion
          path: out/*.aix